{% set version = '0.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bigmemory.sri
  version: {{ version|replace("-", "_") }}

source:
  fn: bigmemory.sri_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/bigmemory.sri_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bigmemory.sri/bigmemory.sri_{{ version }}.tar.gz
  sha256: 55403252d8bae9627476d1f553236ea5dc7aa6e54da6980526a6cdc66924e155

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('bigmemory.sri')"           # [not win]
    - "\"%R%\" -e \"library('bigmemory.sri')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bigmemory.sri
  license: LGPL-3 | Apache 2.0
  summary: This package provides a shared resource interface for the bigmemory and synchronicity
    packages.
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
