travis:
  secure:
    BINSTAR_TOKEN: BwualbkES7NoecQOVyPhUmiAFTh5aSBCUXD23WU4EyVQeBkyzumCIF7+5qCrBTvZoar64cc3itWRll6jw9xdfwnIbsvlne/lPiojNxdfLqIRax1cc2IAKCVoTG4+X5iT+8gq0wt8VaC6JHcmmiu5i0/oFKZunZOo6XGj4++kQLRcF0sQvHNAfvENBEZ1ak9dUCC+ZLcTb/uLzEgfIa2+7LMr1e+HbdwN46eBC5tSMyDaeNz00oQogBNQbVQ0lFllIRbpmi9MbXx3kEOin7TNGHTFAV3AX8oh/kZ7oSHf2l+3iZYdU/B4lh0vzx+cUOXplq3y5AnxP73Su2o/eE3Sfn+4zYHxBRWdBZgOi2a6Cw7e7ZBrssJ8pjC/k4DPyfRyKZpuL8he/X9kKP0Coi3arN5fHc6u4q6ha/nOZjI0ZzSlVr2/MNZR5lbu6zoeuQWicKxF8hxzZoUpNLkyVTIoIldD2ayC9yLMEPTe8iyVJbcY6+nBRaI4qkFCvzp6hlnWuzleOFhckZIBKQpwaJgVkuom8BcAbPJ17zE1gBKn+aOuRRXEVa2VDul3Kldphtvf4s48bK93covWOqqm7amVE9QJoMjqvpbh1TOQh97QiRXMTr+pdZJOVCFLLg+VmM3LvqYSzl5L0rEREwPC/iEb3/XiBQUlCBlXdH+YVEkfuUY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
