travis:
  secure:
    BINSTAR_TOKEN: XBL+6bpGF4icLPDmTeJJZsqmKRe42JEl3aP4MwpwTEFjca1ASzB0rxmh2AcN5iA0i8BNJ5gzVhK3uOY88CyPFcvONNLEujGRHq9ymj5CSSI4yJJtW96JOLF63ua2JQUQyJ5CmicwEWIk6e982u8A7GZAc/sZVUxafOa5kep1BuobQmvFd/uT3wih4am5XBDnpwYcUvGpjlyTdqA/pPxHjEyJeVuN5zUWYJ9Zu12rdURzZBRXcCZ+E7qxJlQbMnmJWsRwkCCpE6EDJou/Q5QDUWBwHBY/lt8zd5b4mloAU0FJLGugR6BLCfAsfbYebBptPRtpFL99AMmPQIo7gtBu5e6WAlI3/yADIZ0gOC8i+gqE+YnhzcBRL1yOxTAsQEBz0fG6Pis9lXt3gll3DRXxB+i9bKvn4ydoF/T9au2KjZbeCl5Bykn3M0itua9VopjjmrsUE6ZdM/xV3M/bZNB96xpLeArOsnPMvIQL8Zv/kcGsg/fDLQc2tv73hD4Fq/Gnap4WfAZrEcXnuEQhetFHgVcZD3ohXatFCumgerYzuj9hUx69O84l78+bzr7fOptZHH2YZ/0gPYuTrJnJYyktG2JNiBZ7trMXgx1eHpzL3pm5lGgDDd9S6abLhgWSrFuF4ZuyW/G/d4R6QN5a2kHPf4bTBEMJIJlHHDoV+BWerYc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
