travis:
  secure:
    BINSTAR_TOKEN: 469kDPNEhjx4fa5iw4w41JoWUhIMys+03EG5xEN/wj+AYgdRm4jlytYcjjJgZGG02APZW0T605W6R4Ejt84T/5BjEr+AwTEn6QlbldDeNFuefuBklS60wkeKKEBCUGj/UjVXyFnven7vL/E3/4CAwlY+UdJbq+xyONoZNNkOPns8IGG27NqVfpJ9yfiM/Wrvfbu9sRZXAAtiotTIDJjW1LFj7HTusEm+V/dDPvoLEkLjD7b+XCOpx0pCHgBHFMlD7OtLBmpxk4nfjGL19Pz5IzuXDTlaNaQihMkQs5B8NLQRK9jtrAK22exgnL5pv++CvmaRlhkL/RFcTU9XZjHtauy9OoI2RCrSMOW9SuRGrYy6+j+ugAP9C266jxdmBebRFMwuk8/1OOlhSmq3v/LnmTY3AVtiR0yX/zQGdDWGhNZZFR7O2qrHWVbZCnwgNLx6PorHRR7cYy4CySgXqyKXiqqHxri8Ap4UULF/eqDya7sVZGDilyWzs22TWN88MQCp8dDaA5HUclTUS7PnXeMXNf6LiHH5/py0W0bADW2a5kFvPzzntV1xkbI15a33uVM7oqSvFbxpevTMXDv/2UmhMp9EILBET2JsuSfjCfdOuE67RnpOuoZ//iMUcBvblRigGGmmv21rXcEt8KGY1mV9yMekyBuz+Vb8yltB/M20b6E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
