travis:
  secure:
    BINSTAR_TOKEN: sreZWw+orfznKS2H2h5QiEPcDj541FKV+0naVWCeZtMPhdHX24HO/SQWjWykHbSxo6UEWsEwcNslEHCnimxi0Y0ZSqRpRReQ4s/Sgvu3KlGo3CAAQADH3QKbQZQZf5GLQzeBzasKIKlQl3f6AnAuNl+g2Q0LeiXlM1CBA/hpOLyf9SZFVm0RBPprPMN166q30pG1JQYvvMiZLjqVQXQZ0m2BRdr5EYcUM/9iooTwU3rJU3ro8fp9R59heCQD7lRa3zjqkmLz2ZDgwjxkHFgLX/R1KohEQrwiJXGxQwOx58Cn+M8vs4PxMtuDKabmsDLswsqxvvqsZrjPBjKiemINclVbqm9NZGNH3vVNsbpiwbt6i0wYbqVBWtFVrJkmtg8KzWFb65OriQhWQ7aOzWX870zvIVWBleqSSOR7yFs9pnorvStBnD9W4fL01kgUU3VP/oj3gyP2l4RtJ20ky/y/O92bycwCoyA4+ZSveHyW28gNanqjJWqcKeq2KlxBbP80BFoMQvq0YX7GJDAFJewsTJHLZVSmEzIGXs11lj56gqbySuL3h1IJP+3NvT9uptoLr3xsjYHZAd31fNQheiJFk/4LHh6C3tioAf1kTJLk0eqLKljaknTsmPZfqeLfzCX+Unp5t/bf6oepiCnk68MiHij0dS4uc5v7phBBa0AR5aI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
